<a href="https://colab.research.google.com/github/octane312/Machine-Learning/blob/main/Car_Price_OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ONE HOT ENCODING**

## **IMPORTING MODULES**

In [39]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.compose import ColumnTransformer

## **LOADING DATASET**

In [40]:
d=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/refs/heads/master/ML/5_one_hot_encoding/Exercise/carprices.csv")
d

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

Encoding the Car Model

In [41]:
le=LabelEncoder()
d["Car Model"]=le.fit_transform(d["Car Model"])
print(d)

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5


## **SEPERATING DATA SET**

In [42]:
x=d[["Car Model","Mileage","Age(yrs)"]]
Y=d["Sell Price($)"]

Applying One Hot Encoding

In [43]:
ct = ColumnTransformer([('Car Model', OneHotEncoder(),[0])], remainder='passthrough')
X = ct.fit_transform(x)
X=X[:,1:]
print(X)

[[1.00e+00 0.00e+00 6.90e+04 6.00e+00]
 [1.00e+00 0.00e+00 3.50e+04 3.00e+00]
 [1.00e+00 0.00e+00 5.70e+04 5.00e+00]
 [1.00e+00 0.00e+00 2.25e+04 2.00e+00]
 [1.00e+00 0.00e+00 4.60e+04 4.00e+00]
 [0.00e+00 0.00e+00 5.90e+04 5.00e+00]
 [0.00e+00 0.00e+00 5.20e+04 5.00e+00]
 [0.00e+00 0.00e+00 7.20e+04 6.00e+00]
 [0.00e+00 0.00e+00 9.10e+04 8.00e+00]
 [0.00e+00 1.00e+00 6.70e+04 6.00e+00]
 [0.00e+00 1.00e+00 8.30e+04 7.00e+00]
 [0.00e+00 1.00e+00 7.90e+04 7.00e+00]
 [0.00e+00 1.00e+00 5.90e+04 5.00e+00]]


## **FITTING MODEL**

In [44]:
model=LinearRegression()
model.fit(X,Y)

LinearRegression()

## **PREDICTING USING MODEL**

Here I take two test case

1.   Mercedes Benz that is 4 years old with mileage 45000
2.   BMW X5 that is 7 year old with mileage 86000

In [45]:
Y_pred=model.predict(X)
print(f"Test case 1 : {model.predict([[0,1,45000,4]])}\nTest case 1 : {model.predict([[1,0,86000,7]])}")


Test case 1 : [36991.31721062]
Test case 1 : [11080.74313219]


## **EVALUATING MODEL**

In [46]:
print(f"Accuracy Score : {model.score(X,Y_pred)}")

Accuracy Score : 1.0
