<a href="https://colab.research.google.com/github/octane312/Machine-Learning/blob/main/Min_Max_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MIN-MAX SCALING, STANDARDIZING AND NORMALIZING**

## **IMPORTING MODULES**

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler,Normalizer

## **CREATING DATA**

In [16]:
np.random.seed(32)
X=np.random.randn(7,5)

## **MIN-MAX SCALING**

In [17]:
MMS=MinMaxScaler()
X_MMS=MMS.fit_transform(X)

## **STARDARDIZING**

In [19]:
STD=StandardScaler()
X_STD=STD.fit_transform(X)

## **NORMALIZING**

In [21]:
NRZ=Normalizer()
X_NRZ=NRZ.fit_transform(X)

## **PRINTING RESULTS**

In [22]:
print(f"Dataset : \n{X}\n\nMin-Max Scaled Result : \n{X_MMS}\n\nStandardized Result : \n{X_STD}\n\nNormalizer Result : \n{X_NRZ}")

Dataset : 
[[-0.34889445  0.98370343  0.58092283  0.07028444  0.77753268]
 [ 0.58195875  1.47179053  1.66318101 -0.26117712 -0.68867681]
 [-0.69492326  1.94042346  1.80541519  0.45631385 -0.57481204]
 [ 0.1141805   1.51358077  0.35113184 -0.08893321  0.91695423]
 [ 0.50564513 -0.81527111  0.38915095 -0.42496247  0.03962315]
 [-0.52796392 -0.51030368 -0.88828515  1.08762473  0.67339226]
 [-1.06731704  1.21804998  3.36371255 -0.8322534  -0.34034838]]

Min-Max Scaled Result : 
[[0.43559882 0.65282073 0.34553358 0.47010163 0.91316713]
 [1.         0.82994018 0.60006292 0.29745444 0.        ]
 [0.2257923  1.         0.63351406 0.67117138 0.0709159 ]
 [0.71637355 0.84510522 0.29149051 0.38717051 1.        ]
 [0.95372901 0.         0.30043198 0.21214416 0.45359111]
 [0.32702421 0.11066808 0.         1.         0.84830764]
 [0.         0.73786156 1.         0.         0.21694177]]

Standardized Result : 
[[-0.24858053  0.15722937 -0.361248    0.1197194   1.06147062]
 [ 1.36319016  0.65281595  